version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    entrypoint: /myapp/entrypoint.sh
    volumes:
      - .:/myapp
    tmpfs: /myapp/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - RAILS_ENV
      - RAILS_LOG_TO_STDOUT=present
    restart: always
